#!/usr/bin/env bash

# Adjust storage rights
echo "Change storage owner rights";
chown -R www-data:www-data /srv/www/storage

# Start cron
echo "Start Cron";
/etc/init.d/cron start

/usr/bin/supervisord
