<?php

return [
    [
        'translation' => 'Administrēšana',
        'unique_key' => 'administration',
        'sequence' => 10,
        'parent_id' => null,
        'description' => 'test test test test',
    ],
    [
        'translation' => 'Klasifikatori',
        'unique_key' => 'classifier',
        'sequence' => 10,
        'parent_id' => 'administration',
        'description' => 'test test test test',
    ],
    [
        'translation' => 'Iestādes klasifikators',
        'unique_key' => 'institution_classifier',
        'sequence' => 15,
        'parent_id' => 'administration',
        'description' => 'Iestādes klasifikators',
    ],
    [
        'translation' => 'Izvēlnes pārvaldība',
        'unique_key' => 'ui_menu',
        'sequence' => 20,
        'parent_id' => 'administration',
        'description' => 'test test test test',
    ],
    [
        'translation' => 'Paziņojumi',
        'unique_key' => 'notification',
        'sequence' => 30,
        'parent_id' => 'administration',
        'description' => 'test test test test',
    ],
    [
        'translation' => 'Ģeoproduktu katalogs',
        'unique_key' => 'geoproduct',
        'sequence' => 40,
        'parent_id' => 'administration',
        'description' => 'test test test test',
    ],
    [
        'translation' => 'Lietotāju pārvaldība',
        'unique_key' => 'user_management',
        'sequence' => 50,
        'parent_id' => 'administration',
        'description' => 'Lietotāju pārvaldība',
    ],
    [
        'translation' => 'Visi iestatijumi',
        'unique_key' => 'system_setting',
        'sequence' => 60,
        'parent_id' => 'administration',
        'description' => 'Visi iestatijumi',
    ],
    [
        'translation' => 'Spraudņi',
        'unique_key' => 'plugins',
        'sequence' => 70,
        'parent_id' => 'administration',
        'description' => 'Spraudņi',
    ],
    [
        'translation' => 'Failu formāti',
        'unique_key' => 'system_settings_file',
        'sequence' => 80,
        'parent_id' => 'administration',
        'description' => 'Failu formāti',
    ],
    [
        'translation' => 'Atjaunojamu Lejupielādes datņu apstrādes veidi',
        'unique_key' => 'processing_type',
        'sequence' => 90,
        'parent_id' => 'administration',
        'description' => 'Atjaunojamu Lejupielādes datņu apstrādes veidi',
    ],
    [
        'translation' => 'Fona pārbaude',
        'unique_key' => 'background_task',
        'sequence' => 100,
        'parent_id' => 'administration',
        'description' => 'Fona pārbaude',
    ],
    [
        'translation' => 'Atskaites',
        'unique_key' => 'geoproduct_report',
        'sequence' => 110,
        'parent_id' => 'administration',
        'description' => 'Atskaites',
    ],
    [
        'translation' => 'Licenču pārvaldība',
        'unique_key' => 'licence_management',
        'sequence' => 120,
        'parent_id' => 'administration',
        'description' => 'Licenču pārvaldība',
    ],
    [
        'translation' => 'Tematiskās lietotāju grupas',
        'unique_key' => 'thematic_user_group',
        'sequence' => 130,
        'parent_id' => 'administration',
        'description' => 'Tematiskās lietotāju grupas',
    ],
    [
        'translation' => 'Pasūtīto Licenču / licenču līgumu saraksts',
        'unique_key' => 'ordered_licence',
        'sequence' => 140,
        'parent_id' => 'administration',
        'description' => 'Pasūtīto Licenču / licenču līgumu saraksts',
    ],
    [
        'translation' => 'Datu Turētājs - Pasūtījumi',
        'unique_key' => 'orders_data_holder',
        'sequence' => 150,
        'parent_id' => 'administration',
        'description' => 'Datu Turētājs - Pasūtījumi',
    ],
    [
        'translation' => 'Tooltip redaktors',
        'unique_key' => 'tooltip',
        'sequence' => 160,
        'parent_id' => 'administration',
        'description' => 'Tooltip redaktors',
    ],

    [
        'translation' => 'Kartes pārlūks',
        'unique_key' => 'map_browser',
        'sequence' => 5,
        'parent_id' => null,
        'description' => 'Atver KP, Saturu nevajag, hardkodētā pēc būtības',
    ],
    [
        'translation' => 'Plānošanas dokumenti',
        'unique_key' => 'tapis',
        'sequence' => 10,
        'parent_id' => 'map_browser',
        'description' => 'Pāriet uz KP un ieslēdz Plānošanās dokumentus',
        'url' => '/main?documents=open'
    ],
    [
        'translation' => 'Ģeoprodukti',
        'unique_key' => 'geoproducts_public',
        'sequence' => 20,
        'parent_id' => 'map_browser',
        'description' => 'Pāriet uz KP un atver ģeoproduktu katalogu',
        'url' => '/main?geoproduct=open'
    ],
    [
        'translation' => 'Metadatu katalogs',
        'unique_key' => 'metadata',
        'sequence' => 30,
        'parent_id' => 'map_browser',
        'description' => 'Atver metadatu katalogu, saturs nav vajadzīgs',
        'url' => env('GEONETWORK_BASE_URI') . '/geonetwork/srv/eng/catalog.search#/home'
    ],


    [
        'translation' => 'Privātuma politika',
        'unique_key' => 'private_politic',
        'sequence' => 10,
        'parent_id' => null,
        'is_footer' => true,
        'description' => 'test test test test',
    ],
    [
        'translation' => 'Sīkdatnes',
        'unique_key' => 'cookies',
        'sequence' => 20,
        'parent_id' => null,
        'is_footer' => true,
        'description' => 'test test test test',
    ],
];
