#!/usr/bin/env bash

# Wait for database connection
composer install

max_retries=10

#while true
#do
#    php artisan app:db-health-check --quiet
#    if [[ $? -ne 0 ]]; then
#        if [[ "$max_retries" -lt 0 ]]; then
#            echo "Failed to establish DB connection with 10 retries"
#            exit 1
#        else
#            max_retries=$((max_retries - 1))
#            echo "Retrying database connection..."
#            sleep 5
#        fi
#    else
#        echo "Database connection established!"
#        break
#    fi
#done

# Adjust storage rights
chown -R www-data:www-data /srv/www/storage
chown -R www-data:www-data /srv/www/public

# Perform migrations
php artisan migrate --force

php artisan optimize:clear

# Start cron
/etc/init.d/cron start

/usr/bin/supervisord
